<script>
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { fade, fly } from 'svelte/transition';
	import { getAgents } from '$lib/services/agent-service.js';

	let mounted = false;
	let selectedAgent = null;
	let agents = [];
	let messages = [];
	let messageInput = '';
	let showAgentSelect = true;
	let isLoading = false;
	let chatContainer;
	let outputItems = [];

	// Get session ID from URL if exists
	const sessionId = $page.params.id;

	onMount(async () => {
		mounted = true;
		await loadAgents();

		if (sessionId) {
			// Load existing session
			loadSession(sessionId);
		}
	});

	async function loadAgents() {
		try {
			const filter = {
				pager: { page: 1, size: 50, count: 0 }
			};
			const response = await getAgents(filter, true);
			agents = response?.items?.map((t) => ({ ...t })) || [];
		} catch (error) {
			console.error('Failed to load agents:', error);
		}
	}

	function loadSession(id) {
		// Mock loading session data
		showAgentSelect = false;
		selectedAgent = agents[0];
		messages = [
			{
				id: '1',
				content: 'Hello! How can I help you today?',
				isUser: false,
				timestamp: new Date(),
				agent: selectedAgent
			}
		];
	}

	function selectAgent(agent) {
		selectedAgent = agent;
		showAgentSelect = false;
		// Add welcome message
		messages = [
			{
				id: Date.now().toString(),
				content: `Hello! I'm ${agent.name}. ${agent.description}`,
				isUser: false,
				timestamp: new Date(),
				agent: agent
			}
		];
	}

	function changeAgent() {
		showAgentSelect = true;
		selectedAgent = null;
		messages = [];
		outputItems = [];
	}

	async function sendMessage() {
		if (!messageInput.trim() || isLoading) return;

		const userMessage = {
			id: Date.now().toString(),
			content: messageInput.trim(),
			isUser: true,
			timestamp: new Date()
		};

		messages = [...messages, userMessage];
		const currentInput = messageInput;
		messageInput = '';
		isLoading = true;

		// Scroll to bottom
		setTimeout(() => {
			if (chatContainer) {
				chatContainer.scrollTop = chatContainer.scrollHeight;
			}
		}, 100);

		// Simulate AI response
		setTimeout(
			() => {
				const aiResponse = {
					id: (Date.now() + 1).toString(),
					content: generateMockResponse(currentInput),
					isUser: false,
					timestamp: new Date(),
					agent: selectedAgent
				};

				messages = [...messages, aiResponse];
				isLoading = false;

				// Simulate adding output items
				if (Math.random() > 0.7) {
					addMockOutput();
				}

				setTimeout(() => {
					if (chatContainer) {
						chatContainer.scrollTop = chatContainer.scrollHeight;
					}
				}, 100);
			},
			1000 + Math.random() * 2000
		);
	}

	function generateMockResponse(input) {
		const responses = [
			'I understand your question. Let me help you with that.',
			"That's an interesting point. Here's what I think...",
			"Based on your input, I'd suggest the following approach:",
			'Great question! Let me break this down for you:',
			'I can help you with that. Here are some key points to consider:'
		];

		return (
			responses[Math.floor(Math.random() * responses.length)] +
			' ' +
			'This is a mock response to demonstrate the chat functionality. In a real implementation, this would be connected to your AI service.'
		);
	}

	function addMockOutput() {
		const outputTypes = ['image', 'chart', 'code', 'document'];
		const type = outputTypes[Math.floor(Math.random() * outputTypes.length)];

		const newOutput = {
			id: Date.now().toString(),
			type: type,
			title: `Generated ${type.charAt(0).toUpperCase() + type.slice(1)}`,
			timestamp: new Date(),
			content: `Mock ${type} content generated by AI`
		};

		outputItems = [...outputItems, newOutput];
	}

	function removeOutput(outputId) {
		outputItems = outputItems.filter((item) => item.id !== outputId);
	}

	function handleKeydown(event) {
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			sendMessage();
		}
	}

	function goBack() {
		goto('/workspace/sessions');
	}

	function formatTime(timestamp) {
		return timestamp.toLocaleTimeString('en-US', {
			hour: '2-digit',
			minute: '2-digit'
		});
	}
</script>

<div class="chat-page">
	{#if mounted}
		{#if showAgentSelect}
			<!-- Agent Selection -->
			<div class="agent-selection" in:fade={{ duration: 600 }}>
				<div class="selection-header">
					<button class="back-btn" on:click={goBack}>
						<i class="fas fa-arrow-left"></i>
						Back to Sessions
					</button>
					<h1 class="selection-title">Choose Your AI Assistant</h1>
					<p class="selection-subtitle">Select an agent to start your conversation</p>
				</div>

				<div class="agents-grid" in:fly={{ y: 30, duration: 800, delay: 200 }}>
					{#each agents as agent, index}
						<div
							class="agent-card"
							on:click={() => selectAgent(agent)}
							on:keydown={(e) => e.key === 'Enter' && selectAgent(agent)}
							role="button"
							tabindex="0"
							in:fly={{ y: 30, duration: 600, delay: 100 * index }}
						>
							<div class="agent-avatar">
								<i class="fas fa-robot"></i>
							</div>
							<div class="agent-info">
								<h3 class="agent-name">{agent.name}</h3>
								<p class="agent-description">{agent.description}</p>
							</div>
							<div class="select-arrow">
								<i class="fas fa-arrow-right"></i>
							</div>
						</div>
					{/each}
				</div>
			</div>
		{:else}
			<!-- Chat Interface -->
			<div class="chat-interface" in:fade={{ duration: 600 }}>
				<!-- Chat Header -->
				<div class="chat-header">
					<div class="header-left">
						<button class="back-btn" on:click={goBack}>
							<i class="fas fa-arrow-left"></i>
						</button>
						<div class="agent-info">
							<div class="agent-avatar-small">
								<i class="fas fa-robot"></i>
							</div>
							<div>
								<h3 class="current-agent-name">{selectedAgent?.name}</h3>
								<span class="agent-status">
									<i class="fas fa-circle online"></i>
									Online
								</span>
							</div>
						</div>
					</div>
					<div class="header-actions">
						<button class="header-btn" on:click={changeAgent} title="Change Agent">
							<i class="fas fa-exchange-alt"></i>
						</button>
						<button class="header-btn" title="Session Settings">
							<i class="fas fa-cog"></i>
						</button>
					</div>
				</div>

				<!-- Chat Content -->
				<div class="chat-content">
					<!-- Messages Panel -->
					<div class="messages-panel">
						<div class="messages-container" bind:this={chatContainer}>
							{#each messages as message (message.id)}
								<div
									class="message {message.isUser ? 'user-message' : 'ai-message'}"
									in:fly={{ y: 20, duration: 400 }}
								>
									{#if !message.isUser}
										<div class="message-avatar">
											<i class="fas fa-robot"></i>
										</div>
									{/if}
									<div class="message-content">
										<div class="message-bubble">
											<p>{message.content}</p>
										</div>
										<div class="message-meta">
											<span class="message-time">{formatTime(message.timestamp)}</span>
											{#if !message.isUser}
												<span class="message-agent">{message.agent?.name}</span>
											{/if}
										</div>
									</div>
									{#if message.isUser}
										<div class="message-avatar user-avatar">
											<i class="fas fa-user"></i>
										</div>
									{/if}
								</div>
							{/each}

							{#if isLoading}
								<div class="message ai-message" in:fade={{ duration: 300 }}>
									<div class="message-avatar">
										<i class="fas fa-robot"></i>
									</div>
									<div class="message-content">
										<div class="typing-indicator">
											<div class="typing-dots">
												<span></span>
												<span></span>
												<span></span>
											</div>
										</div>
									</div>
								</div>
							{/if}
						</div>

						<!-- Message Input -->
						<div class="message-input-area">
							<div class="input-container">
								<textarea
									bind:value={messageInput}
									on:keydown={handleKeydown}
									placeholder="Type your message..."
									class="message-input"
									rows="1"
									disabled={isLoading}
								></textarea>
								<button
									class="send-btn"
									on:click={sendMessage}
									disabled={!messageInput.trim() || isLoading}
								>
									<i class="fas fa-paper-plane"></i>
								</button>
							</div>
						</div>
					</div>

					<!-- Output Canvas Panel -->
					<div class="output-panel">
						<div class="output-header">
							<h3>
								<i class="fas fa-palette me-2"></i>
								Output Canvas
							</h3>
							<span class="output-count">{outputItems.length} items</span>
						</div>

						<div class="output-content">
							{#if outputItems.length > 0}
								{#each outputItems as item (item.id)}
									<div class="output-item" in:fly={{ x: 20, duration: 400 }}>
										<div class="output-item-header">
											<div class="output-icon">
												{#if item.type === 'image'}
													<i class="fas fa-image"></i>
												{:else if item.type === 'chart'}
													<i class="fas fa-chart-bar"></i>
												{:else if item.type === 'code'}
													<i class="fas fa-code"></i>
												{:else}
													<i class="fas fa-file"></i>
												{/if}
											</div>
											<div class="output-info">
												<h4>{item.title}</h4>
												<span class="output-time">{formatTime(item.timestamp)}</span>
											</div>
											<button class="remove-btn" on:click={() => removeOutput(item.id)}>
												<i class="fas fa-times"></i>
											</button>
										</div>
										<div class="output-preview">
											<p>{item.content}</p>
										</div>
									</div>
								{/each}
							{:else}
								<div class="output-placeholder">
									<i class="fas fa-palette"></i>
									<p>Output Canvas</p>
									<span>Generated content will appear here</span>
								</div>
							{/if}
						</div>
					</div>
				</div>
			</div>
		{/if}
	{/if}
</div>

<style>
	.chat-page {
		height: 100vh;
		background: #f8f9fa;
		overflow: hidden;
	}

	/* Agent Selection Styles */
	.agent-selection {
		height: 100vh;
		background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
		overflow-y: auto;
		padding: 2rem;
	}

	.selection-header {
		text-align: center;
		margin-bottom: 3rem;
		max-width: 800px;
		margin-left: auto;
		margin-right: auto;
	}

	.back-btn {
		background: none;
		border: none;
		color: #667eea;
		font-size: 1rem;
		cursor: pointer;
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.5rem 1rem;
		border-radius: 8px;
		transition: all 0.3s ease;
		margin-bottom: 2rem;
	}

	.back-btn:hover {
		background: rgba(102, 126, 234, 0.1);
	}

	.selection-title {
		font-size: 2.5rem;
		font-weight: 700;
		color: #2c3e50;
		margin-bottom: 1rem;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
	}

	.selection-subtitle {
		font-size: 1.2rem;
		color: #7f8c8d;
	}

	.agents-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
		gap: 1.5rem;
		max-width: 1000px;
		margin: 0 auto;
	}

	.agent-card {
		background: white;
		border-radius: 12px;
		padding: 1.5rem;
		cursor: pointer;
		transition: all 0.3s ease;
		box-shadow: 0 4px 6px rgba(0, 0, 0, 0.07);
		border: 1px solid rgba(255, 255, 255, 0.2);
		display: flex;
		align-items: center;
	}

	.agent-card:hover {
		transform: translateY(-4px);
		box-shadow: 0 12px 30px rgba(0, 0, 0, 0.15);
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		color: white;
	}

	.agent-avatar {
		width: 60px;
		height: 60px;
		border-radius: 12px;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		margin-right: 1rem;
		flex-shrink: 0;
	}

	.agent-card:hover .agent-avatar {
		background: rgba(255, 255, 255, 0.2);
	}

	.agent-avatar i {
		font-size: 1.5rem;
		color: white;
	}

	.agent-info {
		flex-grow: 1;
	}

	.agent-name {
		font-size: 1.2rem;
		font-weight: 600;
		margin-bottom: 0.5rem;
		color: inherit;
	}

	.agent-description {
		font-size: 0.9rem;
		color: #7f8c8d;
		margin: 0;
		line-height: 1.4;
	}

	.agent-card:hover .agent-description {
		color: rgba(255, 255, 255, 0.8);
	}

	.select-arrow {
		margin-left: 1rem;
		flex-shrink: 0;
	}

	.select-arrow i {
		font-size: 1rem;
		color: #bdc3c7;
		transition: all 0.3s ease;
	}

	.agent-card:hover .select-arrow i {
		color: white;
		transform: translateX(3px);
	}

	/* Chat Interface Styles */
	.chat-interface {
		height: 100vh;
		display: flex;
		flex-direction: column;
	}

	.chat-header {
		background: white;
		border-bottom: 1px solid #e9ecef;
		padding: 1rem 1.5rem;
		display: flex;
		align-items: center;
		justify-content: space-between;
		flex-shrink: 0;
	}

	.header-left {
		display: flex;
		align-items: center;
		gap: 1rem;
	}

	.agent-avatar-small {
		width: 40px;
		height: 40px;
		border-radius: 8px;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		margin-right: 0.75rem;
	}

	.agent-avatar-small i {
		color: white;
		font-size: 1rem;
	}

	.current-agent-name {
		font-size: 1rem;
		font-weight: 600;
		color: #2c3e50;
		margin: 0 0 0.25rem 0;
	}

	.agent-status {
		font-size: 0.8rem;
		color: #7f8c8d;
		display: flex;
		align-items: center;
		gap: 0.25rem;
	}

	.agent-status .online {
		color: #27ae60;
		font-size: 0.6rem;
	}

	.header-actions {
		display: flex;
		gap: 0.5rem;
	}

	.header-btn {
		background: none;
		border: none;
		padding: 0.5rem;
		border-radius: 6px;
		color: #7f8c8d;
		cursor: pointer;
		transition: all 0.3s ease;
	}

	.header-btn:hover {
		background: #f8f9fa;
		color: #667eea;
	}

	.chat-content {
		flex: 1;
		display: flex;
		overflow: hidden;
	}

	.messages-panel {
		flex: 1;
		display: flex;
		flex-direction: column;
		border-right: 1px solid #e9ecef;
	}

	.messages-container {
		flex: 1;
		overflow-y: auto;
		padding: 1rem;
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.message {
		display: flex;
		align-items: flex-start;
		gap: 0.75rem;
		max-width: 80%;
	}

	.user-message {
		align-self: flex-end;
		flex-direction: row-reverse;
	}

	.ai-message {
		align-self: flex-start;
	}

	.message-avatar {
		width: 32px;
		height: 32px;
		border-radius: 50%;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
	}

	.user-avatar {
		background: linear-gradient(135deg, #2ecc71 0%, #27ae60 100%);
	}

	.message-avatar i {
		color: white;
		font-size: 0.8rem;
	}

	.message-content {
		flex: 1;
	}

	.message-bubble {
		background: white;
		border-radius: 12px;
		padding: 0.75rem 1rem;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
		border: 1px solid #e9ecef;
	}

	.user-message .message-bubble {
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		color: white;
	}

	.message-bubble p {
		margin: 0;
		line-height: 1.4;
	}

	.message-meta {
		margin-top: 0.25rem;
		font-size: 0.75rem;
		color: #bdc3c7;
		display: flex;
		gap: 0.5rem;
	}

	.user-message .message-meta {
		justify-content: flex-end;
	}

	.typing-indicator {
		padding: 0.75rem 1rem;
	}

	.typing-dots {
		display: flex;
		gap: 0.25rem;
	}

	.typing-dots span {
		width: 6px;
		height: 6px;
		border-radius: 50%;
		background: #bdc3c7;
		animation: typing 1.4s infinite ease-in-out;
	}

	.typing-dots span:nth-child(1) {
		animation-delay: -0.32s;
	}
	.typing-dots span:nth-child(2) {
		animation-delay: -0.16s;
	}

	@keyframes typing {
		0%,
		80%,
		100% {
			transform: scale(0);
		}
		40% {
			transform: scale(1);
		}
	}

	.message-input-area {
		padding: 1rem;
		background: white;
		border-top: 1px solid #e9ecef;
	}

	.input-container {
		display: flex;
		gap: 0.75rem;
		align-items: flex-end;
		max-width: 100%;
	}

	.message-input {
		flex: 1;
		border: 1px solid #e9ecef;
		border-radius: 12px;
		padding: 0.75rem 1rem;
		font-family: inherit;
		font-size: 0.9rem;
		resize: none;
		max-height: 120px;
		min-height: 40px;
		background: #f8f9fa;
		transition: all 0.3s ease;
	}

	.message-input:focus {
		outline: none;
		border-color: #667eea;
		background: white;
		box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
	}

	.message-input:disabled {
		background: #e9ecef;
		color: #7f8c8d;
	}

	.send-btn {
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		color: white;
		border: none;
		width: 40px;
		height: 40px;
		border-radius: 50%;
		cursor: pointer;
		transition: all 0.3s ease;
		display: flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
	}

	.send-btn:hover:not(:disabled) {
		transform: scale(1.05);
		box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
	}

	.send-btn:disabled {
		background: #bdc3c7;
		cursor: not-allowed;
		transform: none;
	}

	/* Output Panel Styles */
	.output-panel {
		width: 300px;
		background: white;
		display: flex;
		flex-direction: column;
		overflow: hidden;
	}

	.output-header {
		padding: 1rem 1.5rem;
		border-bottom: 1px solid #e9ecef;
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	.output-header h3 {
		font-size: 1rem;
		font-weight: 600;
		color: #2c3e50;
		margin: 0;
		display: flex;
		align-items: center;
	}

	.output-count {
		font-size: 0.8rem;
		color: #7f8c8d;
		background: #f8f9fa;
		padding: 0.25rem 0.5rem;
		border-radius: 12px;
	}

	.output-content {
		flex: 1;
		overflow-y: auto;
		padding: 1rem;
	}

	.output-item {
		background: #f8f9fa;
		border-radius: 8px;
		padding: 1rem;
		margin-bottom: 1rem;
		border: 1px solid #e9ecef;
	}

	.output-item-header {
		display: flex;
		align-items: center;
		margin-bottom: 0.75rem;
	}

	.output-icon {
		width: 32px;
		height: 32px;
		border-radius: 6px;
		background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		margin-right: 0.75rem;
		flex-shrink: 0;
	}

	.output-icon i {
		color: white;
		font-size: 0.9rem;
	}

	.output-info {
		flex: 1;
	}

	.output-info h4 {
		font-size: 0.9rem;
		font-weight: 600;
		color: #2c3e50;
		margin: 0 0 0.25rem 0;
	}

	.output-time {
		font-size: 0.75rem;
		color: #7f8c8d;
	}

	.remove-btn {
		background: none;
		border: none;
		color: #bdc3c7;
		cursor: pointer;
		padding: 0.25rem;
		border-radius: 4px;
		transition: all 0.3s ease;
	}

	.remove-btn:hover {
		color: #e74c3c;
		background: rgba(231, 76, 60, 0.1);
	}

	.output-preview {
		background: white;
		border-radius: 6px;
		padding: 0.75rem;
		border: 1px solid #e9ecef;
	}

	.output-preview p {
		margin: 0;
		font-size: 0.8rem;
		color: #7f8c8d;
		line-height: 1.3;
	}

	.output-placeholder {
		text-align: center;
		padding: 3rem 1rem;
		color: #bdc3c7;
	}

	.output-placeholder i {
		font-size: 2.5rem;
		margin-bottom: 1rem;
	}

	.output-placeholder p {
		font-size: 1rem;
		font-weight: 600;
		margin-bottom: 0.5rem;
		color: #7f8c8d;
	}

	.output-placeholder span {
		font-size: 0.8rem;
	}

	@media (max-width: 768px) {
		.output-panel {
			display: none;
		}

		.selection-title {
			font-size: 2rem;
		}

		.agents-grid {
			grid-template-columns: 1fr;
			padding: 0 1rem;
		}

		.agent-card {
			padding: 1rem;
		}

		.message {
			max-width: 95%;
		}
	}
</style>
